### ISSUE TITLE
Flip Board

### ISSUE THREAD

**Issue by AzeemIdrisi** [marcizhu/readme-chess#14]
The chess board should flip after every move.
It makes the experience better.

`gameboard.transform(chess.flip_vertical)`

**Comment by marcizhu** [comment]
Hey @AzeemIdrisi, thanks for your feature request. I agree it could be a good idea to allow flipping the board so you always see it for the current player's point of view. Unfortunately, it is not as simple as you suggested since you would need to apply that rotation only for black's turn, and you'd also have to make sure that the board generation is flipped so that the coordinates are valid. Ideally, any user should be able to opt-out of this feature by changing the settings file.

The code is somewhat well-written and easy to follow. If you feel like implementing it, PRs are always welcome 😄

**Comment by marcizhu** [comment]
@Hitro147 implemented this feature in PR #16 so I'll close this issue. Thanks!
