### ISSUE TITLE
The chess pieces are hard to identify

### ISSUE THREAD

**Issue by doodla** [marcizhu/readme-chess#15]
<img width="69" alt="image" src="https://github.com/marcizhu/readme-chess/assets/3683106/33fb8fd2-894a-4045-a9d8-109fc38d038e">

The king and the pawn are very similar. As are the bishop and pawn.

A chess piece option with the clarity below would be amazing.

<img width="522" alt="image" src="https://github.com/marcizhu/readme-chess/assets/3683106/ab411417-1a67-4516-af07-0233dca0039b">

**Comment by marcizhu** [comment]
I agree, I had quite a few people raise similar complaints over the past couple of years, where people argued that the rook and the queen looked quite similar, for example.

The main issue here is finding a chess set that looks good both on dark mode as well as in light mode, since the user could be using any of those and there's no way to detect it. Unfortunately, that fact alone rules out most of the chess sets (like the one you posted), since the black pieces would be barely visible in dark mode. This is why currently black pieces are dark blue and white pieces are grey-ish.

Another important aspect is licensing. The chess set must be licensed under a permissive license that doesn't require attribution and allows redistribution, since by putting the images in this repo I'm effectively redistributing them, and I have no way of giving attribution. This is also a limiting factor in finding a better set...

Let's keep this issue open for the time being. I'll look for better sets and we can use this thread to discuss/vote which ones are better. Thanks for reporting this! 😄

**Comment by marcizhu** [comment]
Hey @doodla, I changed the chess set used in https://github.com/marcizhu/marcizhu and I think it's way easier to identify the chess pieces now:
<img width="711" alt="image" src="https://github.com/marcizhu/readme-chess/assets/6199781/07e5388b-5efa-49dc-bdde-cc6d4619c18d">

All pieces are recognizable in dark and light modes. I'll do some tests and if everything goes as expected I will update this repo and close this issue. In the mean time, feel free to propose other chess sets!
