### ISSUE TITLE
Can you help me set up my chess game please?

### ISSUE THREAD

**Issue by RusMermaid** [marcizhu/readme-chess#7]

**Comment by RusMermaid** [comment]
Please, look at my READ.MD file and see why it's not working

**Comment by marcizhu** [comment]
I've looked at the README.md and everything looks fine. However, I see that you didn't copy the GitHub Actions necessary for this to work. Instead of manually copying files, I strongly recommend creating a new repo from this template which will contain all necessary files, including the ones you're missing.

After having copied the GitHub Actions files and renamed the folder just as the README.md says, if you open an issue with `Chess: Start new game` it will work.

**Comment by RusMermaid** [comment]
I just copied the folder except the README.md file cuz I want other stuff in it too

**Comment by marcizhu** [comment]
As I already said, don't copy the files manually or you might miss something as it happened. Also, just follow the steps described in the README file of this project. Copying some files won't make it magically work. The files in this repo are just that, text files. You need to properly configure GitHub Actions so those script are executed and the chess board updates after each move.

**Comment by RusMermaid** [comment]
Yes, I changed the pieces, and recopied your template and it magicly worked, come and see and make a move lol
